# Generated by Django 4.0.3 on 2022-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('GOOGLE', 'Google'), ('APPLE', 'Apple'), ('GITHUB', 'GitHub'), ('UNSPLASH', 'Unsplash')], default='REMOTE', max_length=100),
        ),
    ]
