# Generated by Django 4.0.3 on 2022-03-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('UNSPLASH', 'Unsplash')], default='REMOTE', max_length=100),
        ),
    ]
