from .property_add_views import *
from .property_detail_views import *
from .property_favourite_views import *
from .property_filter_views import *
from .property_image_views import * 
from .property_list_views import *
from .property_ownership_views import *
from .property_recommender_views import *
from .property_sale_views import *